---
- name: Install Remote Desktop Software
  ansible.builtin.apt:
    name:
      - "{{ desktop_environment }} 
      - xrdp
  tags:
    - desktop

- name: Authorize to ssh login with ssh key
  authorized_key:
    user: "{{ dev_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set password for ubuntu user to ubuntu
  ansible.builtin.user:
    name: "{{ dev_user }}" 
    password: '$6$gbKufjzNjcEJjxFh$0D4Zucaz4L06Gs.Ny/wVykM1lGeWuF21DKvjsm77yUY9Z62G5lONmqz3UTlpCGHA99f36bO.dRUCTNIcspFv41' 


- name: Install git
  ansible.builtin.apt:                                                         
    name:                                                                      
      - git

- name: checkout git repos
  ansible.builtin.git:
    repo: 'https://github.com/Bassinator/ansible-role-development-vm.git'
    dest: ~/dev/ansible-role-development-vm

- name: Install pycharm
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/python/pycharm-community-2023.3.3-aarch64.tar.gz
    dest: /opt
    remote_src: true
