---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - debug:
        var: hostvars

    - name: "Include ansible-role-developemnt-vm"
      ansible.builtin.include_role:
        name: "ansible-role-developemnt-vm"
