---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
